networks:
  dev:

services:
  frontend:
    build: ./client
    ports:
      - '6666:6666'
    volumes:
      - ./client:/app
    networks:
      - dev

  backend:
    build: ./server
    ports:
      - '666:666'
    volumes:
      - ./server:/app
      - /path/on/host/uploads:/usr/src/app/uploads
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /path/on/host/uploads:/usr/src/app/uploads
      - ./certbot:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - dev
