version: '3.8'

networks:
  dev:

services:
  frontend:
    build: ./client
    networks:
      - dev

  backend:
    build: ./server
    environment:
      - PORT=666
      - MONGO_DB_URL=mongodb://mongo:27017/gravity
    depends_on:
      - mongo
    volumes:
      - ./server/uploads:/usr/src/app/uploads
    networks:
      - dev

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./server/uploads:/usr/src/app/uploads:ro
      - ./certbot:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - dev

volumes:
  mongo_data:
